apiVersion: pages.cloudflare.m.crossplane.io/v1beta1
kind: Domain
metadata:
  namespace: default
  name: my-pages-domain
spec:
  forProvider:
    accountId: "your-account-id"
    projectName: "my-static-site"
    domain: "www.example.com"
  providerConfigRef:
    name: default
