apiVersion: zone.cloudflare.m.crossplane.io/v1beta1
kind: Zone
metadata:
  namespace: default
  name: example
spec:
  forProvider:
    name: test-domain.com
    paused: true
    jumpStart: false
    settings:
      developmentMode: "on"
  providerConfigRef:
    name: example