apiVersion: zone.cloudflare.crossplane.io/v1alpha1
kind: Zone
metadata:
  name: example
spec:
  deletionPolicy: Orphan
  forProvider:
    name: test-domain.com
    paused: true
    jumpStart: false
    settings:
      developmentMode: "on"
  providerConfigRef:
    name: example