apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-credentials
  namespace: crossplane-system
type: Opaque
stringData:
  # Replace with your actual Cloudflare API token
  # The token should have Zone:Zone:Read, Zone:Zone:Edit, Zone:DNS:Edit permissions
  token: "your-cloudflare-api-token-here"
---
apiVersion: cloudflare.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: cloudflare-credentials
      key: token