# Build using pre-built binary approach
FROM ghcr.io/rossigee/provider-mailgun:v0.6.6 as base

# Use distroless as minimal base image
FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=base /provider .
USER 65532:65532

ENTRYPOINT ["/provider"]