//go:build !ignore_autogenerated

/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessApplication) DeepCopyInto(out *AccessApplication) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessApplication.
func (in *AccessApplication) DeepCopy() *AccessApplication {
	if in == nil {
		return nil
	}
	out := new(AccessApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccessApplication) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessApplicationFooterLink) DeepCopyInto(out *AccessApplicationFooterLink) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessApplicationFooterLink.
func (in *AccessApplicationFooterLink) DeepCopy() *AccessApplicationFooterLink {
	if in == nil {
		return nil
	}
	out := new(AccessApplicationFooterLink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessApplicationLandingPageDesign) DeepCopyInto(out *AccessApplicationLandingPageDesign) {
	*out = *in
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.ImageURL != nil {
		in, out := &in.ImageURL, &out.ImageURL
		*out = new(string)
		**out = **in
	}
	if in.ButtonColor != nil {
		in, out := &in.ButtonColor, &out.ButtonColor
		*out = new(string)
		**out = **in
	}
	if in.ButtonTextColor != nil {
		in, out := &in.ButtonTextColor, &out.ButtonTextColor
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessApplicationLandingPageDesign.
func (in *AccessApplicationLandingPageDesign) DeepCopy() *AccessApplicationLandingPageDesign {
	if in == nil {
		return nil
	}
	out := new(AccessApplicationLandingPageDesign)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessApplicationList) DeepCopyInto(out *AccessApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccessApplication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessApplicationList.
func (in *AccessApplicationList) DeepCopy() *AccessApplicationList {
	if in == nil {
		return nil
	}
	out := new(AccessApplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccessApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessApplicationObservation) DeepCopyInto(out *AccessApplicationObservation) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
	if in.AllowedIdps != nil {
		in, out := &in.AllowedIdps, &out.AllowedIdps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FooterLinks != nil {
		in, out := &in.FooterLinks, &out.FooterLinks
		*out = make([]AccessApplicationFooterLink, len(*in))
		copy(*out, *in)
	}
	if in.LandingPageDesign != nil {
		in, out := &in.LandingPageDesign, &out.LandingPageDesign
		*out = new(AccessApplicationLandingPageDesign)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessApplicationObservation.
func (in *AccessApplicationObservation) DeepCopy() *AccessApplicationObservation {
	if in == nil {
		return nil
	}
	out := new(AccessApplicationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessApplicationParameters) DeepCopyInto(out *AccessApplicationParameters) {
	*out = *in
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
	if in.SessionDuration != nil {
		in, out := &in.SessionDuration, &out.SessionDuration
		*out = new(string)
		**out = **in
	}
	if in.AllowedIdps != nil {
		in, out := &in.AllowedIdps, &out.AllowedIdps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AutoRedirectToIdentity != nil {
		in, out := &in.AutoRedirectToIdentity, &out.AutoRedirectToIdentity
		*out = new(bool)
		**out = **in
	}
	if in.EnableBindingCookie != nil {
		in, out := &in.EnableBindingCookie, &out.EnableBindingCookie
		*out = new(bool)
		**out = **in
	}
	if in.AppLauncherVisible != nil {
		in, out := &in.AppLauncherVisible, &out.AppLauncherVisible
		*out = new(bool)
		**out = **in
	}
	if in.ServiceAuth401Redirect != nil {
		in, out := &in.ServiceAuth401Redirect, &out.ServiceAuth401Redirect
		*out = new(bool)
		**out = **in
	}
	if in.SkipInterstitial != nil {
		in, out := &in.SkipInterstitial, &out.SkipInterstitial
		*out = new(bool)
		**out = **in
	}
	if in.LogoURL != nil {
		in, out := &in.LogoURL, &out.LogoURL
		*out = new(string)
		**out = **in
	}
	if in.BgColor != nil {
		in, out := &in.BgColor, &out.BgColor
		*out = new(string)
		**out = **in
	}
	if in.HeaderBgColor != nil {
		in, out := &in.HeaderBgColor, &out.HeaderBgColor
		*out = new(string)
		**out = **in
	}
	if in.FooterLinks != nil {
		in, out := &in.FooterLinks, &out.FooterLinks
		*out = make([]AccessApplicationFooterLink, len(*in))
		copy(*out, *in)
	}
	if in.LandingPageDesign != nil {
		in, out := &in.LandingPageDesign, &out.LandingPageDesign
		*out = new(AccessApplicationLandingPageDesign)
		(*in).DeepCopyInto(*out)
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessApplicationParameters.
func (in *AccessApplicationParameters) DeepCopy() *AccessApplicationParameters {
	if in == nil {
		return nil
	}
	out := new(AccessApplicationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessApplicationSpec) DeepCopyInto(out *AccessApplicationSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessApplicationSpec.
func (in *AccessApplicationSpec) DeepCopy() *AccessApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(AccessApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessApplicationStatus) DeepCopyInto(out *AccessApplicationStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessApplicationStatus.
func (in *AccessApplicationStatus) DeepCopy() *AccessApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(AccessApplicationStatus)
	in.DeepCopyInto(out)
	return out
}
