//go:build !ignore_autogenerated

/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrowserTTL) DeepCopyInto(out *BrowserTTL) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrowserTTL.
func (in *BrowserTTL) DeepCopy() *BrowserTTL {
	if in == nil {
		return nil
	}
	out := new(BrowserTTL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheKey) DeepCopyInto(out *CacheKey) {
	*out = *in
	if in.CacheByDeviceType != nil {
		in, out := &in.CacheByDeviceType, &out.CacheByDeviceType
		*out = new(bool)
		**out = **in
	}
	if in.IgnoreQueryStringsOrder != nil {
		in, out := &in.IgnoreQueryStringsOrder, &out.IgnoreQueryStringsOrder
		*out = new(bool)
		**out = **in
	}
	if in.CacheDeceptionArmor != nil {
		in, out := &in.CacheDeceptionArmor, &out.CacheDeceptionArmor
		*out = new(bool)
		**out = **in
	}
	if in.CustomKey != nil {
		in, out := &in.CustomKey, &out.CustomKey
		*out = new(CustomKey)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheKey.
func (in *CacheKey) DeepCopy() *CacheKey {
	if in == nil {
		return nil
	}
	out := new(CacheKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheReserve) DeepCopyInto(out *CacheReserve) {
	*out = *in
	if in.Eligible != nil {
		in, out := &in.Eligible, &out.Eligible
		*out = new(bool)
		**out = **in
	}
	if in.MinimumFileSize != nil {
		in, out := &in.MinimumFileSize, &out.MinimumFileSize
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheReserve.
func (in *CacheReserve) DeepCopy() *CacheReserve {
	if in == nil {
		return nil
	}
	out := new(CacheReserve)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheRule) DeepCopyInto(out *CacheRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheRule.
func (in *CacheRule) DeepCopy() *CacheRule {
	if in == nil {
		return nil
	}
	out := new(CacheRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CacheRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheRuleList) DeepCopyInto(out *CacheRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CacheRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheRuleList.
func (in *CacheRuleList) DeepCopy() *CacheRuleList {
	if in == nil {
		return nil
	}
	out := new(CacheRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CacheRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheRuleObservation) DeepCopyInto(out *CacheRuleObservation) {
	*out = *in
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = new(string)
		**out = **in
	}
	if in.CreatedOn != nil {
		in, out := &in.CreatedOn, &out.CreatedOn
		*out = new(string)
		**out = **in
	}
	if in.ModifiedOn != nil {
		in, out := &in.ModifiedOn, &out.ModifiedOn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheRuleObservation.
func (in *CacheRuleObservation) DeepCopy() *CacheRuleObservation {
	if in == nil {
		return nil
	}
	out := new(CacheRuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheRuleParameters) DeepCopyInto(out *CacheRuleParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int)
		**out = **in
	}
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(bool)
		**out = **in
	}
	if in.EdgeTTL != nil {
		in, out := &in.EdgeTTL, &out.EdgeTTL
		*out = new(EdgeTTL)
		(*in).DeepCopyInto(*out)
	}
	if in.BrowserTTL != nil {
		in, out := &in.BrowserTTL, &out.BrowserTTL
		*out = new(BrowserTTL)
		(*in).DeepCopyInto(*out)
	}
	if in.ServeStale != nil {
		in, out := &in.ServeStale, &out.ServeStale
		*out = new(ServeStale)
		(*in).DeepCopyInto(*out)
	}
	if in.CacheKey != nil {
		in, out := &in.CacheKey, &out.CacheKey
		*out = new(CacheKey)
		(*in).DeepCopyInto(*out)
	}
	if in.CacheReserve != nil {
		in, out := &in.CacheReserve, &out.CacheReserve
		*out = new(CacheReserve)
		(*in).DeepCopyInto(*out)
	}
	if in.OriginCacheControl != nil {
		in, out := &in.OriginCacheControl, &out.OriginCacheControl
		*out = new(bool)
		**out = **in
	}
	if in.RespectStrongETags != nil {
		in, out := &in.RespectStrongETags, &out.RespectStrongETags
		*out = new(bool)
		**out = **in
	}
	if in.OriginErrorPagePassthru != nil {
		in, out := &in.OriginErrorPagePassthru, &out.OriginErrorPagePassthru
		*out = new(bool)
		**out = **in
	}
	if in.AdditionalCacheablePorts != nil {
		in, out := &in.AdditionalCacheablePorts, &out.AdditionalCacheablePorts
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.ReadTimeout != nil {
		in, out := &in.ReadTimeout, &out.ReadTimeout
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheRuleParameters.
func (in *CacheRuleParameters) DeepCopy() *CacheRuleParameters {
	if in == nil {
		return nil
	}
	out := new(CacheRuleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheRuleSpec) DeepCopyInto(out *CacheRuleSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheRuleSpec.
func (in *CacheRuleSpec) DeepCopy() *CacheRuleSpec {
	if in == nil {
		return nil
	}
	out := new(CacheRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheRuleStatus) DeepCopyInto(out *CacheRuleStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheRuleStatus.
func (in *CacheRuleStatus) DeepCopy() *CacheRuleStatus {
	if in == nil {
		return nil
	}
	out := new(CacheRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomKey) DeepCopyInto(out *CustomKey) {
	*out = *in
	if in.Query != nil {
		in, out := &in.Query, &out.Query
		*out = new(CustomKeyQuery)
		(*in).DeepCopyInto(*out)
	}
	if in.Header != nil {
		in, out := &in.Header, &out.Header
		*out = new(CustomKeyHeader)
		(*in).DeepCopyInto(*out)
	}
	if in.Cookie != nil {
		in, out := &in.Cookie, &out.Cookie
		*out = new(CustomKeyFields)
		(*in).DeepCopyInto(*out)
	}
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(CustomKeyUser)
		(*in).DeepCopyInto(*out)
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(CustomKeyHost)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomKey.
func (in *CustomKey) DeepCopy() *CustomKey {
	if in == nil {
		return nil
	}
	out := new(CustomKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomKeyFields) DeepCopyInto(out *CustomKeyFields) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CheckPresence != nil {
		in, out := &in.CheckPresence, &out.CheckPresence
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomKeyFields.
func (in *CustomKeyFields) DeepCopy() *CustomKeyFields {
	if in == nil {
		return nil
	}
	out := new(CustomKeyFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomKeyHeader) DeepCopyInto(out *CustomKeyHeader) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CheckPresence != nil {
		in, out := &in.CheckPresence, &out.CheckPresence
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeOrigin != nil {
		in, out := &in.ExcludeOrigin, &out.ExcludeOrigin
		*out = new(bool)
		**out = **in
	}
	if in.Contains != nil {
		in, out := &in.Contains, &out.Contains
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomKeyHeader.
func (in *CustomKeyHeader) DeepCopy() *CustomKeyHeader {
	if in == nil {
		return nil
	}
	out := new(CustomKeyHeader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomKeyHost) DeepCopyInto(out *CustomKeyHost) {
	*out = *in
	if in.Resolved != nil {
		in, out := &in.Resolved, &out.Resolved
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomKeyHost.
func (in *CustomKeyHost) DeepCopy() *CustomKeyHost {
	if in == nil {
		return nil
	}
	out := new(CustomKeyHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomKeyQuery) DeepCopyInto(out *CustomKeyQuery) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.All != nil {
		in, out := &in.All, &out.All
		*out = new(bool)
		**out = **in
	}
	if in.Ignore != nil {
		in, out := &in.Ignore, &out.Ignore
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomKeyQuery.
func (in *CustomKeyQuery) DeepCopy() *CustomKeyQuery {
	if in == nil {
		return nil
	}
	out := new(CustomKeyQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomKeyUser) DeepCopyInto(out *CustomKeyUser) {
	*out = *in
	if in.DeviceType != nil {
		in, out := &in.DeviceType, &out.DeviceType
		*out = new(bool)
		**out = **in
	}
	if in.Geo != nil {
		in, out := &in.Geo, &out.Geo
		*out = new(bool)
		**out = **in
	}
	if in.Lang != nil {
		in, out := &in.Lang, &out.Lang
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomKeyUser.
func (in *CustomKeyUser) DeepCopy() *CustomKeyUser {
	if in == nil {
		return nil
	}
	out := new(CustomKeyUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeTTL) DeepCopyInto(out *EdgeTTL) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(int)
		**out = **in
	}
	if in.StatusCodeTTL != nil {
		in, out := &in.StatusCodeTTL, &out.StatusCodeTTL
		*out = make([]StatusCodeTTL, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeTTL.
func (in *EdgeTTL) DeepCopy() *EdgeTTL {
	if in == nil {
		return nil
	}
	out := new(EdgeTTL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServeStale) DeepCopyInto(out *ServeStale) {
	*out = *in
	if in.DisableStaleWhileUpdating != nil {
		in, out := &in.DisableStaleWhileUpdating, &out.DisableStaleWhileUpdating
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServeStale.
func (in *ServeStale) DeepCopy() *ServeStale {
	if in == nil {
		return nil
	}
	out := new(ServeStale)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusCodeRange) DeepCopyInto(out *StatusCodeRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusCodeRange.
func (in *StatusCodeRange) DeepCopy() *StatusCodeRange {
	if in == nil {
		return nil
	}
	out := new(StatusCodeRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusCodeTTL) DeepCopyInto(out *StatusCodeTTL) {
	*out = *in
	if in.StatusCodeValue != nil {
		in, out := &in.StatusCodeValue, &out.StatusCodeValue
		*out = new(int)
		**out = **in
	}
	if in.StatusCodeRange != nil {
		in, out := &in.StatusCodeRange, &out.StatusCodeRange
		*out = new(StatusCodeRange)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusCodeTTL.
func (in *StatusCodeTTL) DeepCopy() *StatusCodeTTL {
	if in == nil {
		return nil
	}
	out := new(StatusCodeTTL)
	in.DeepCopyInto(out)
	return out
}
