//go:build !ignore_autogenerated

/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BotManagement) DeepCopyInto(out *BotManagement) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BotManagement.
func (in *BotManagement) DeepCopy() *BotManagement {
	if in == nil {
		return nil
	}
	out := new(BotManagement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BotManagement) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BotManagementList) DeepCopyInto(out *BotManagementList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BotManagement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BotManagementList.
func (in *BotManagementList) DeepCopy() *BotManagementList {
	if in == nil {
		return nil
	}
	out := new(BotManagementList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BotManagementList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BotManagementObservation) DeepCopyInto(out *BotManagementObservation) {
	*out = *in
	if in.EnableJS != nil {
		in, out := &in.EnableJS, &out.EnableJS
		*out = new(bool)
		**out = **in
	}
	if in.FightMode != nil {
		in, out := &in.FightMode, &out.FightMode
		*out = new(bool)
		**out = **in
	}
	if in.SBFMDefinitelyAutomated != nil {
		in, out := &in.SBFMDefinitelyAutomated, &out.SBFMDefinitelyAutomated
		*out = new(string)
		**out = **in
	}
	if in.SBFMLikelyAutomated != nil {
		in, out := &in.SBFMLikelyAutomated, &out.SBFMLikelyAutomated
		*out = new(string)
		**out = **in
	}
	if in.SBFMVerifiedBots != nil {
		in, out := &in.SBFMVerifiedBots, &out.SBFMVerifiedBots
		*out = new(string)
		**out = **in
	}
	if in.SBFMStaticResourceProtection != nil {
		in, out := &in.SBFMStaticResourceProtection, &out.SBFMStaticResourceProtection
		*out = new(bool)
		**out = **in
	}
	if in.OptimizeWordpress != nil {
		in, out := &in.OptimizeWordpress, &out.OptimizeWordpress
		*out = new(bool)
		**out = **in
	}
	if in.SuppressSessionScore != nil {
		in, out := &in.SuppressSessionScore, &out.SuppressSessionScore
		*out = new(bool)
		**out = **in
	}
	if in.AutoUpdateModel != nil {
		in, out := &in.AutoUpdateModel, &out.AutoUpdateModel
		*out = new(bool)
		**out = **in
	}
	if in.UsingLatestModel != nil {
		in, out := &in.UsingLatestModel, &out.UsingLatestModel
		*out = new(bool)
		**out = **in
	}
	if in.AIBotsProtection != nil {
		in, out := &in.AIBotsProtection, &out.AIBotsProtection
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BotManagementObservation.
func (in *BotManagementObservation) DeepCopy() *BotManagementObservation {
	if in == nil {
		return nil
	}
	out := new(BotManagementObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BotManagementParameters) DeepCopyInto(out *BotManagementParameters) {
	*out = *in
	if in.EnableJS != nil {
		in, out := &in.EnableJS, &out.EnableJS
		*out = new(bool)
		**out = **in
	}
	if in.FightMode != nil {
		in, out := &in.FightMode, &out.FightMode
		*out = new(bool)
		**out = **in
	}
	if in.SBFMDefinitelyAutomated != nil {
		in, out := &in.SBFMDefinitelyAutomated, &out.SBFMDefinitelyAutomated
		*out = new(string)
		**out = **in
	}
	if in.SBFMLikelyAutomated != nil {
		in, out := &in.SBFMLikelyAutomated, &out.SBFMLikelyAutomated
		*out = new(string)
		**out = **in
	}
	if in.SBFMVerifiedBots != nil {
		in, out := &in.SBFMVerifiedBots, &out.SBFMVerifiedBots
		*out = new(string)
		**out = **in
	}
	if in.SBFMStaticResourceProtection != nil {
		in, out := &in.SBFMStaticResourceProtection, &out.SBFMStaticResourceProtection
		*out = new(bool)
		**out = **in
	}
	if in.OptimizeWordpress != nil {
		in, out := &in.OptimizeWordpress, &out.OptimizeWordpress
		*out = new(bool)
		**out = **in
	}
	if in.SuppressSessionScore != nil {
		in, out := &in.SuppressSessionScore, &out.SuppressSessionScore
		*out = new(bool)
		**out = **in
	}
	if in.AutoUpdateModel != nil {
		in, out := &in.AutoUpdateModel, &out.AutoUpdateModel
		*out = new(bool)
		**out = **in
	}
	if in.AIBotsProtection != nil {
		in, out := &in.AIBotsProtection, &out.AIBotsProtection
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BotManagementParameters.
func (in *BotManagementParameters) DeepCopy() *BotManagementParameters {
	if in == nil {
		return nil
	}
	out := new(BotManagementParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BotManagementSpec) DeepCopyInto(out *BotManagementSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BotManagementSpec.
func (in *BotManagementSpec) DeepCopy() *BotManagementSpec {
	if in == nil {
		return nil
	}
	out := new(BotManagementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BotManagementStatus) DeepCopyInto(out *BotManagementStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BotManagementStatus.
func (in *BotManagementStatus) DeepCopy() *BotManagementStatus {
	if in == nil {
		return nil
	}
	out := new(BotManagementStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimit) DeepCopyInto(out *RateLimit) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimit.
func (in *RateLimit) DeepCopy() *RateLimit {
	if in == nil {
		return nil
	}
	out := new(RateLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RateLimit) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitAction) DeepCopyInto(out *RateLimitAction) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(int)
		**out = **in
	}
	if in.Response != nil {
		in, out := &in.Response, &out.Response
		*out = new(RateLimitActionResponse)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitAction.
func (in *RateLimitAction) DeepCopy() *RateLimitAction {
	if in == nil {
		return nil
	}
	out := new(RateLimitAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitActionResponse) DeepCopyInto(out *RateLimitActionResponse) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitActionResponse.
func (in *RateLimitActionResponse) DeepCopy() *RateLimitActionResponse {
	if in == nil {
		return nil
	}
	out := new(RateLimitActionResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitCorrelate) DeepCopyInto(out *RateLimitCorrelate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitCorrelate.
func (in *RateLimitCorrelate) DeepCopy() *RateLimitCorrelate {
	if in == nil {
		return nil
	}
	out := new(RateLimitCorrelate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitKeyValue) DeepCopyInto(out *RateLimitKeyValue) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitKeyValue.
func (in *RateLimitKeyValue) DeepCopy() *RateLimitKeyValue {
	if in == nil {
		return nil
	}
	out := new(RateLimitKeyValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitList) DeepCopyInto(out *RateLimitList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RateLimit, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitList.
func (in *RateLimitList) DeepCopy() *RateLimitList {
	if in == nil {
		return nil
	}
	out := new(RateLimitList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RateLimitList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitObservation) DeepCopyInto(out *RateLimitObservation) {
	*out = *in
	in.Match.DeepCopyInto(&out.Match)
	if in.Bypass != nil {
		in, out := &in.Bypass, &out.Bypass
		*out = make([]RateLimitKeyValue, len(*in))
		copy(*out, *in)
	}
	in.Action.DeepCopyInto(&out.Action)
	if in.Correlate != nil {
		in, out := &in.Correlate, &out.Correlate
		*out = new(RateLimitCorrelate)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitObservation.
func (in *RateLimitObservation) DeepCopy() *RateLimitObservation {
	if in == nil {
		return nil
	}
	out := new(RateLimitObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitParameters) DeepCopyInto(out *RateLimitParameters) {
	*out = *in
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	in.Match.DeepCopyInto(&out.Match)
	if in.Bypass != nil {
		in, out := &in.Bypass, &out.Bypass
		*out = make([]RateLimitKeyValue, len(*in))
		copy(*out, *in)
	}
	in.Action.DeepCopyInto(&out.Action)
	if in.Correlate != nil {
		in, out := &in.Correlate, &out.Correlate
		*out = new(RateLimitCorrelate)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitParameters.
func (in *RateLimitParameters) DeepCopy() *RateLimitParameters {
	if in == nil {
		return nil
	}
	out := new(RateLimitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitRequestMatcher) DeepCopyInto(out *RateLimitRequestMatcher) {
	*out = *in
	if in.Methods != nil {
		in, out := &in.Methods, &out.Methods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Schemes != nil {
		in, out := &in.Schemes, &out.Schemes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.URLPattern != nil {
		in, out := &in.URLPattern, &out.URLPattern
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitRequestMatcher.
func (in *RateLimitRequestMatcher) DeepCopy() *RateLimitRequestMatcher {
	if in == nil {
		return nil
	}
	out := new(RateLimitRequestMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitResponseMatcher) DeepCopyInto(out *RateLimitResponseMatcher) {
	*out = *in
	if in.Statuses != nil {
		in, out := &in.Statuses, &out.Statuses
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.OriginTraffic != nil {
		in, out := &in.OriginTraffic, &out.OriginTraffic
		*out = new(bool)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]RateLimitResponseMatcherHeader, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitResponseMatcher.
func (in *RateLimitResponseMatcher) DeepCopy() *RateLimitResponseMatcher {
	if in == nil {
		return nil
	}
	out := new(RateLimitResponseMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitResponseMatcherHeader) DeepCopyInto(out *RateLimitResponseMatcherHeader) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitResponseMatcherHeader.
func (in *RateLimitResponseMatcherHeader) DeepCopy() *RateLimitResponseMatcherHeader {
	if in == nil {
		return nil
	}
	out := new(RateLimitResponseMatcherHeader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitSpec) DeepCopyInto(out *RateLimitSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitSpec.
func (in *RateLimitSpec) DeepCopy() *RateLimitSpec {
	if in == nil {
		return nil
	}
	out := new(RateLimitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitStatus) DeepCopyInto(out *RateLimitStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitStatus.
func (in *RateLimitStatus) DeepCopy() *RateLimitStatus {
	if in == nil {
		return nil
	}
	out := new(RateLimitStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitTrafficMatcher) DeepCopyInto(out *RateLimitTrafficMatcher) {
	*out = *in
	in.Request.DeepCopyInto(&out.Request)
	if in.Response != nil {
		in, out := &in.Response, &out.Response
		*out = new(RateLimitResponseMatcher)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitTrafficMatcher.
func (in *RateLimitTrafficMatcher) DeepCopy() *RateLimitTrafficMatcher {
	if in == nil {
		return nil
	}
	out := new(RateLimitTrafficMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Turnstile) DeepCopyInto(out *Turnstile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Turnstile.
func (in *Turnstile) DeepCopy() *Turnstile {
	if in == nil {
		return nil
	}
	out := new(Turnstile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Turnstile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TurnstileList) DeepCopyInto(out *TurnstileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Turnstile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TurnstileList.
func (in *TurnstileList) DeepCopy() *TurnstileList {
	if in == nil {
		return nil
	}
	out := new(TurnstileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TurnstileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TurnstileObservation) DeepCopyInto(out *TurnstileObservation) {
	*out = *in
	if in.SiteKey != nil {
		in, out := &in.SiteKey, &out.SiteKey
		*out = new(string)
		**out = **in
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(string)
		**out = **in
	}
	if in.CreatedOn != nil {
		in, out := &in.CreatedOn, &out.CreatedOn
		*out = (*in).DeepCopy()
	}
	if in.ModifiedOn != nil {
		in, out := &in.ModifiedOn, &out.ModifiedOn
		*out = (*in).DeepCopy()
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.BotFightMode != nil {
		in, out := &in.BotFightMode, &out.BotFightMode
		*out = new(bool)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.OffLabel != nil {
		in, out := &in.OffLabel, &out.OffLabel
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TurnstileObservation.
func (in *TurnstileObservation) DeepCopy() *TurnstileObservation {
	if in == nil {
		return nil
	}
	out := new(TurnstileObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TurnstileParameters) DeepCopyInto(out *TurnstileParameters) {
	*out = *in
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.BotFightMode != nil {
		in, out := &in.BotFightMode, &out.BotFightMode
		*out = new(bool)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.OffLabel != nil {
		in, out := &in.OffLabel, &out.OffLabel
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TurnstileParameters.
func (in *TurnstileParameters) DeepCopy() *TurnstileParameters {
	if in == nil {
		return nil
	}
	out := new(TurnstileParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TurnstileSpec) DeepCopyInto(out *TurnstileSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TurnstileSpec.
func (in *TurnstileSpec) DeepCopy() *TurnstileSpec {
	if in == nil {
		return nil
	}
	out := new(TurnstileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TurnstileStatus) DeepCopyInto(out *TurnstileStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TurnstileStatus.
func (in *TurnstileStatus) DeepCopy() *TurnstileStatus {
	if in == nil {
		return nil
	}
	out := new(TurnstileStatus)
	in.DeepCopyInto(out)
	return out
}
