apiVersion: transform.cloudflare.crossplane.io/v1alpha1
kind: Rule
metadata:
  name: example-url-rewrite
  annotations:
    meta.upbound.io/example-id: transform/v1alpha1/rule
spec:
  forProvider:
    # Zone ID where the transform rule should be created
    zone: "your-zone-id"
    
    # Ruleset phase - when this rule should be applied
    phase: "http_request_transform"
    
    # Cloudflare Rules Language expression
    expression: 'http.request.uri.path eq "/old-path"'
    
    # Action to take when expression matches
    action: "rewrite"
    
    # Human-readable description
    description: "Rewrite old path to new path"
    
    # Enable the rule (default: true)
    enabled: true
    
    # Action parameters for URL rewriting
    actionParameters:
      uri:
        path:
          value: "/new-path"
        query:
          value: "utm_source=rewrite&version=v2"
  
  # Reference to provider configuration
  providerConfigRef:
    name: default