apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-cloudflare
  annotations:
    # Marketplace Metadata
    meta.crossplane.io/maintainer: Ross Golder <ross@golder.tech>
    meta.crossplane.io/source: github.com/rossigee/provider-cloudflare
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/category: Infrastructure
    meta.crossplane.io/keywords: cloudflare,dns,cdn,security,waf,firewall,ssl,load-balancer
    meta.crossplane.io/iconURI: https://raw.githubusercontent.com/rossigee/provider-cloudflare/master/.github/cloudflare-icon.svg
    
    # Short description for marketplace listing
    meta.crossplane.io/description: |
      Comprehensive Cloudflare provider for DNS, security, performance, and edge computing resources with 100% test coverage and production-ready reliability.
    
    # Detailed documentation for marketplace
    meta.crossplane.io/readme: |
      # Cloudflare Provider for Crossplane

      `provider-cloudflare` is a comprehensive [Crossplane](https://crossplane.io/) provider that manages Cloudflare resources via their V4 API. It provides complete coverage of Cloudflare's cloud security, performance, and reliability services with production-ready quality and 100% test coverage.

      ## 🚀 Features

      ✅ **Complete Resource Coverage** - All major Cloudflare APIs supported  
      ✅ **100% Test Coverage** - Comprehensive test suite with interface-based testing  
      ✅ **Production Ready** - Used in production environments with proven reliability  
      ✅ **Modern Go** - Go 1.24.5 with latest dependencies and best practices  
      ✅ **Advanced Capabilities** - Geographic routing, traffic steering, advanced caching  
      ✅ **Comprehensive Examples** - Detailed usage examples for all resource types  

      ## 📦 Supported Resources

      ### DNS & Zone Management
      - **Zone** - DNS zones with comprehensive settings
      - **Record** - All DNS record types (A, AAAA, CNAME, MX, TXT, SRV, etc.)

      ### Security & Firewall  
      - **Ruleset** - Modern WAF rulesets with advanced matching
      - **Rule** & **Filter** - Legacy firewall (deprecated)

      ### Load Balancing & Traffic Management
      - **LoadBalancer** - Geographic load balancing with intelligent steering
      - **LoadBalancerPool** - Origin pools with health monitoring
      - **LoadBalancerMonitor** - Health check monitors

      ### Performance & Caching
      - **CacheRule** - Advanced cache rules with custom TTL and eligibility

      ### Applications & Edge Computing
      - **Application** - Spectrum TCP/UDP acceleration
      - **Route** - Worker route bindings for serverless computing

      ### SSL/TLS & Certificates
      - **CustomHostname** - SSL for SaaS certificate management
      - **FallbackOrigin** - SSL for SaaS fallback origins

      ## 🛠 Installation

      ```bash
      kubectl apply -f - <<EOF
      apiVersion: pkg.crossplane.io/v1
      kind: Provider
      metadata:
        name: provider-cloudflare
      spec:
        package: ghcr.io/rossigee/provider-cloudflare:v0.8.8
      EOF
      ```

      ## ⚙️ Configuration

      Configure with your Cloudflare API credentials:

      ```bash
      # Create secret with API token
      kubectl create secret generic cloudflare-secret \
        --from-literal=token="your-cloudflare-api-token"

      # Create ProviderConfig
      kubectl apply -f - <<EOF
      apiVersion: cloudflare.crossplane.io/v1beta1
      kind: ProviderConfig
      metadata:
        name: default
      spec:
        credentials:
          source: Secret
          secretRef:
            namespace: crossplane-system
            name: cloudflare-secret
            key: token
      EOF
      ```

      ## 📖 Documentation

      - [GitHub Repository](https://github.com/rossigee/provider-cloudflare)
      - [API Reference](https://doc.crds.dev/github.com/rossigee/provider-cloudflare)
      - [Examples](https://github.com/rossigee/provider-cloudflare/tree/master/examples)
      - [Cloudflare API Docs](https://developers.cloudflare.com/api/)

      ## 💬 Support

      - [GitHub Issues](https://github.com/rossigee/provider-cloudflare/issues)
      - [Crossplane Slack](https://slack.crossplane.io/) - #providers channel

spec:
  crossplane:
    version: ">=v1.14.0"