name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        default: 'v0.8.4'

env:
  GO_VERSION: '1.24.5'
  # Registry configuration
  PRIMARY_REGISTRY: ghcr.io/rossigee
  ENABLE_HARBOR_PUBLISH: false
  ENABLE_UPBOUND_PUBLISH: false

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Vendor Dependencies
        run: make vendor vendor.check

      - name: Get Version
        id: version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}


      - name: Build and Push Release to Primary Registry
        run: |
          # Build and push to GitHub Container Registry (primary)
          # Ensure all dependencies are installed and packages are built
          make build.all xpkg.build
          make publish \
            REGISTRY_ORGS="${{ env.PRIMARY_REGISTRY }}" \
            XPKG_REG_ORGS="${{ env.PRIMARY_REGISTRY }}" \
            VERSION=${{ steps.version.outputs.version }}

      - name: Build and Push Release to Upbound (Optional)
        if: env.ENABLE_UPBOUND_PUBLISH == 'true'
        run: |
          # Push to Upbound Registry
          make publish XPKG_REG_ORGS="xpkg.upbound.io/crossplane-contrib" \
            VERSION=${{ steps.version.outputs.version }}
        env:
          UPBOUND_TOKEN: ${{ secrets.UPBOUND_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          generate_release_notes: true